name: flutterecommerce4
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.1.0 # Add this line
  permission_handler: ^11.4.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14
  mockito: ^5.4.0
  google_sign_in: ^5.3.0
  http: ^1.3.0
  carousel_slider: 4.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  fl_chart: ^0.35.0
  firebase_crashlytics: ^4.3.5
  url_launcher: ^6.1.10  # Add this line
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cyberpunk_city.jpg
    - assets/icons/google.png
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/ad1.jpg
    - assets/images/ad2.jpg
    - assets/images/ad3.jpg
    - assets/images/default_profile_picture.png
    - assets/images/nick_profile.jpg
    - assets/images/jerick_profile.jpg
    - assets/images/cover.jpg

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/Pixelfy_Variable.ttf
